apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2018-11-20T04:41:37Z
  name: coredns
  namespace: kube-system
  resourceVersion: "3661"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 90b0b342-ec7e-11e8-82fe-9a9e4f58e4b3
